language: node_js
node_js:
  - '4.0'
  - '5.0'
  - '6.0'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  apt: true
  directories:
    - node_modules
notifications:
  email: false
  